/*
 *  
 * The MIT License (MIT)
 * Copyright (c) 2018 Roberto Villarejo Martínez <roberto.villarejo@infotec.mx>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package mx.infotec.dads.kukulkan.shell.commands.chatbot;

import java.io.Serializable;

import com.beust.jcommander.Parameter;

/**
 * The arguments read from console
 * 
 * @author Roberto Villarejo Martínez <roberto.villarejo@infotec.mx>
 *
 */
public class ChatbotArgs implements Serializable {

    private static final long serialVersionUID = 1L;

    @Parameter(names = { "--name" }, description = "The project name", required = true)
    private String name;

    @Parameter(names = { "--version" }, description = "The version of the project")
    private String version = "0.0.1";

    @Parameter(names = { "--description" }, description = "The project description")
    private String description = "Autogenerated with Kukulkan";

    @Parameter(names = { "--license" }, description = "The license")
    private String license = "MIT";

    @Parameter(names = { "--homepage" }, description = "The project homepage")
    private String homepage = "https://github.com/kukulkan-project";

    @Parameter(names = { "--basePackage" }, description = "The project base package", required = true)
    private String basePackage;

    @Parameter(names = { "--author" }, description = "The author name or company name")
    private String author = "Kukulkan";

    @Parameter(names = { "--no-web" }, arity = 0, description = "Disable the support for Web")
    private boolean noWebBot;

    @Parameter(names = { "--no-facebook" }, arity = 0, description = "Disable the support for Facebook")
    private boolean noFacebookBot;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLicense() {
        return license;
    }

    public void setLicense(String license) {
        this.license = license;
    }

    public String getHomepage() {
        return homepage;
    }

    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    public String getBasePackage() {
        return basePackage;
    }

    public void setBasePackage(String basePackage) {
        this.basePackage = basePackage;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public boolean isNoFacebookBot() {
        return noFacebookBot;
    }

    public void setNoFacebookBot(boolean noFacebookBot) {
        this.noFacebookBot = noFacebookBot;
    }

    public boolean isNoWebBot() {
        return noWebBot;
    }

    public void setNoWebBot(boolean noWebBot) {
        this.noWebBot = noWebBot;
    }

}
